image:
  repository: ghcr.io/mumble-voip/mumble-server
  tag: v1.5.735-3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  ports:
    - name: mumble-tcp
      port: 64738
      targetPort: 64738
      protocol: TCP
    - name: mumble-udp
      port: 64738
      targetPort: 64738
      protocol: UDP

persistence:
  enabled: true
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  existingClaim: ""

config: {}
  # server_password: "pass"
  # db_host: "db"

environment:
  acceptUnknownSettings: false
  verbose: false
  chownData: true
  customConfigFile: ""

superuserPassword:
  existingSecret: ""
  existingSecretKey: "password"
  generate: true
  length: 16

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 50m
  #   memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}